collections:
  - name: community.windows
    version: 2.3.0
    source: https://galaxy.ansible.com

  - name: community.postgresql
    version: 3.14.0
    source: https://galaxy.ansible.com

  - name: community.vmware
    version: 5.2.0
    source: https://galaxy.ansible.com

  - name: community.mysql
    version: 3.10.3
    source: https://galaxy.ansible.com

  - name: microsoft.ad
    version: 1.8.0
    source: https://galaxy.ansible.com

  - name: community.network
    version: 5.1.0
    source: https://galaxy.ansible.com

  - name: community.general
    version: 10.1.0
    source: https://galaxy.ansible.com

  - name: community.crypto
    version: 2.22.3
    source: https://galaxy.ansible.com

  - name: community.dns
    version: 3.1.0
    source: https://galaxy.ansible.com

  - name: community.docker
    version: 4.2.0
    source: https://galaxy.ansible.com

  - name: ansible.netcommon
    version: 7.1.0
    source: https://galaxy.ansible.com

  - name: ansible.utils
    version: 5.1.2
    source: https://galaxy.ansible.com

  - name: ansible.windows
    version: 2.3.0
    source: https://galaxy.ansible.com

  - name: chocolatey.chocolatey
    version: 1.5.3
    source: https://galaxy.ansible.com

  - name: it_pappa.win_print
    version: 1.0.0
    source: https://galaxy.ansible.com

  - name: citrix.adc
    version: 1.3.0
    source: https://galaxy.ansible.com